name: e2e Manual

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/e2e.yml
    secrets:
      nixbuild_token: ${{ secrets.NIXBUILD_TOKEN }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      org_token: ${{ secrets.UNION_ORG_PAT }}
